import os
import sqlite3
from pathlib import Path

# The shared DB lives in the red_pill repository storage directory
DB_PATH = Path(os.path.expanduser("~/.gemini/antigravity/storage/events.db"))


def get_connection():
	"""Returns a SQLite connection configured for WAL mode."""
	# Ensure storage dir exists
	DB_PATH.parent.mkdir(parents=True, exist_ok=True)

	conn = sqlite3.connect(str(DB_PATH), timeout=10.0)
	conn.row_factory = sqlite3.Row
	# Enable WAL for high-concurrency between Neon-Link and Red-Pill
	conn.execute("PRAGMA journal_mode=WAL;")
	conn.execute("PRAGMA synchronous=NORMAL;")
	return conn


def init_db():
	"""Initializes the Synaptic Cleft schema."""
	conn = get_connection()
	cursor = conn.cursor()

	# INBOX: Messages coming FROM the outside world (Neon-Link) TO the Core (Red-Pill)
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS inbox (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			channel TEXT NOT NULL,          -- e.g., 'telegram', 'discord'
			channel_user_id TEXT NOT NULL,  -- e.g., telegram user ID
			cascade_id TEXT,                -- Target conversation UUID (if known)
			payload TEXT NOT NULL,          -- JSON serialized payload (text, intent, etc.)
			status TEXT DEFAULT 'PENDING',  -- 'PENDING', 'PROCESSING'
			retries INTEGER DEFAULT 0,      -- Number of execution attempts
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# OUTBOX: Messages generated BY the Core (Red-Pill) to be sent TO the outside world
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS outbox (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			channel TEXT NOT NULL,
			channel_user_id TEXT NOT NULL,
			cascade_id TEXT,
			payload TEXT NOT NULL,          -- JSON serialized response
			status TEXT DEFAULT 'PENDING',  -- 'PENDING', 'SENT'
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# DEAD LETTERS: Messages that failed to process 3 times
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS dead_letters (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			original_table TEXT NOT NULL,   -- 'inbox' or 'outbox'
			original_id INTEGER NOT NULL,
			channel TEXT NOT NULL,
			channel_user_id TEXT NOT NULL,
			payload TEXT NOT NULL,
			error_reason TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# HEARTBEAT: Health check tracking
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS system_health (
			service_name TEXT PRIMARY KEY,
			last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# SESSION BINDING: Maps Telegram User ID to IDE Cascade ID
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS telegram_sessions (
			channel_user_id TEXT PRIMARY KEY,
			cascade_id TEXT,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# CASCADE MAPPINGS: Temporary storage for /list and /switch logic
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS cascade_mappings (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			channel_user_id TEXT NOT NULL,
			cascade_id TEXT NOT NULL,
			title TEXT NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# MLS STATE PERSISTENCE: Serialized group states
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS mls_states (
			group_id TEXT PRIMARY KEY,
			state_payload BLOB NOT NULL,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# Initialize Heartbeat rows
	cursor.execute("""
		INSERT OR IGNORE INTO system_health (service_name) 
		VALUES ('red_pill'), ('neon_link')
	""")

	conn.commit()
	conn.close()
	print(f"[+] SQLite WAL Synaptic Cleft initialized at: {DB_PATH}")


if __name__ == "__main__":
	init_db()
