import contextlib
import logging
import os
import sqlite3
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

_DB_PATH: Path | None = None


def set_db_path(path: str | Path):
	"""Configura dinámicamente la ruta de la base de datos (Inyección de dependencias)."""
	global _DB_PATH
	_DB_PATH = Path(os.path.expanduser(str(path)))


def get_db_path() -> Path:
	"""Obtiene la ruta actual, con fallback a variables de entorno o directorio nativo de datos."""
	if _DB_PATH is not None:
		return _DB_PATH

	env_path = os.environ.get("NEON_LINK_DB_PATH")
	if env_path:
		return Path(os.path.expanduser(env_path))

	import platformdirs

	return Path(platformdirs.user_data_dir("neon-link")) / "events.db"


def with_retry(max_retries=3, base_delay=0.5):
	"""Decorator to retry SQLite operations if the database is locked."""
	from functools import wraps

	def decorator(func):
		@wraps(func)
		def wrapper(*args, **kwargs):
			retries = 0
			while retries < max_retries:
				try:
					return func(*args, **kwargs)
				except sqlite3.OperationalError as e:
					if "database is locked" in str(e):
						retries += 1
						if retries == max_retries:
							logger.error(f"Database locked after {max_retries} retries in {func.__name__}")
							raise e
						time.sleep(base_delay * (2 ** (retries - 1)))
					else:
						raise e

		return wrapper

	return decorator


def get_connection():
	"""Returns a SQLite connection configured for WAL mode."""
	db_path = get_db_path()
	# Ensure storage dir exists
	db_path.parent.mkdir(parents=True, exist_ok=True)

	conn = sqlite3.connect(str(db_path), timeout=30.0, isolation_level="IMMEDIATE")
	conn.row_factory = sqlite3.Row
	# Enable WAL for high-concurrency between Neon-Link and Red-Pill
	conn.execute("PRAGMA journal_mode=WAL;")
	conn.execute("PRAGMA synchronous=NORMAL;")
	conn.execute("PRAGMA busy_timeout=5000;")
	return conn


def init_db():
	"""Initializes the Synaptic Cleft schema."""
	conn = get_connection()
	cursor = conn.cursor()

	# INBOX: Messages coming FROM the outside world (Neon-Link) TO the Core (Red-Pill)
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS inbox (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			message_id TEXT UNIQUE,
			channel TEXT NOT NULL,          -- e.g., 'telegram', 'discord'
			channel_user_id TEXT NOT NULL,  -- e.g., telegram user ID
			cascade_id TEXT,                -- Target conversation UUID (if known)
			payload TEXT NOT NULL,          -- JSON serialized payload (text, intent, etc.)
			status TEXT DEFAULT 'PENDING',  -- 'PENDING', 'PROCESSING'
			retries INTEGER DEFAULT 0,      -- Number of execution attempts
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# OUTBOX: Messages generated BY the Core (Red-Pill) to be sent TO the outside world
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS outbox (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			message_id TEXT UNIQUE,
			channel TEXT NOT NULL,
			channel_user_id TEXT NOT NULL,
			cascade_id TEXT,
			payload TEXT NOT NULL,          -- JSON serialized response
			status TEXT DEFAULT 'PENDING',  -- 'PENDING', 'SENT'
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# Add columns if they do not exist (migration)
	with contextlib.suppress(sqlite3.OperationalError):
		cursor.execute("ALTER TABLE inbox ADD COLUMN message_id TEXT UNIQUE")
	with contextlib.suppress(sqlite3.OperationalError):
		cursor.execute("ALTER TABLE outbox ADD COLUMN message_id TEXT UNIQUE")

	# DEAD LETTERS: Messages that failed to process 3 times
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS dead_letters (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			original_table TEXT NOT NULL,   -- 'inbox' or 'outbox'
			original_id INTEGER NOT NULL,
			channel TEXT NOT NULL,
			channel_user_id TEXT NOT NULL,
			payload TEXT NOT NULL,
			error_reason TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# HEARTBEAT: Health check tracking
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS system_health (
			service_name TEXT PRIMARY KEY,
			last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# SESSION BINDING: Maps Telegram User ID to IDE Cascade ID
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS telegram_sessions (
			channel_user_id TEXT PRIMARY KEY,
			cascade_id TEXT,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# CASCADE MAPPINGS: Temporary storage for /list and /switch logic
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS cascade_mappings (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			channel_user_id TEXT NOT NULL,
			cascade_id TEXT NOT NULL,
			title TEXT NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# MLS STATE PERSISTENCE: Serialized group sessions
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS mls_states (
			group_id TEXT PRIMARY KEY,
			state_payload BLOB NOT NULL,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	""")

	# SESSIONS MAPPING: Abstraction layer mapping UUID to physical network endpoints
	cursor.execute("""
		CREATE TABLE IF NOT EXISTS sessions_mapping (
			session_id TEXT PRIMARY KEY,
			channel TEXT NOT NULL,
			channel_user_id TEXT NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			UNIQUE(channel, channel_user_id)
		)
	""")

	# Initialize Heartbeat rows
	cursor.execute("""
		INSERT OR IGNORE INTO system_health (service_name) 
		VALUES ('red_pill'), ('neon_link')
	""")

	conn.commit()
	conn.close()
	print(f"[+] SQLite WAL Synaptic Cleft initialized at: {get_db_path()}")


if __name__ == "__main__":
	init_db()
